sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull kimstebel/thebe-demo-notebook

script:
- cd notebook && docker build -t kimstebek/thebe-demo-notebook .
- echo "$dockercfg" >~/.dockercfg
- docker push 'kimstebel/thebe-demo-notebook'


