sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull kimstebel/thebe-demo-notebook

script:
- cd notebook && docker build -t kimstebek/thebe-demo-notebook .
- echo '{"https://index.docker.io/v1/":{"auth":"' >.dockercfg
- echo "$dockercfg" >>~/.dockercfg
- echo '", "email": "kim.stebel@gmail.com"}}' >>/.dockercfg
- cat ~/.dockercfg
- docker push 'kimstebel/thebe-demo-notebook'

