#!/bin/bash

# stop and remove all docker images

docker stop $( docker ps -a --filter 'name=jupyter' -q)
docker rm $( docker ps -a --filter 'name=jupyter' -q)
docker stop tmpnb
docker rm tmpnb
docker stop proxy
docker rm proxy

# start proxy, tmpnb, thebe

export TOKEN=$( head -c 30 /dev/urandom | xxd -p )
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=proxy jupyter/configurable-http-proxy --default-target http://127.0.0.1:9999
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN --name=tmpnb -v /var/run/docker.sock:/docker.sock jupyter/tmpnb python orchestrate.py --image='jupyter/notebook' --command="ipython notebook --no-browser --NotebookApp.base_url={base_path} --ip=0.0.0.0 --port {port} --NotebookApp.allow_origin=* " --cull-timeout=300 --cull_period=60 --allow_origin="*" --pool_size=2 --pool_name=jupyter
python -m SimpleHTTPServer 8080
#curl -H "Authorization: token $TOKEN" http://localhost:8001/api/routes/thebe -X POST -d '{"target":"http://127.0.0.1:8080"}'


