#!/bin/bash

NOTEBOOK_IMAGE='kimstebel/thebe-demo-notebook'
if [ -z "$1" ] ; then
  POOL_SIZE=50
else
  POOL_SIZE="$1"
fi
TOKEN=$( head -c 30 /dev/urandom | xxd -p )



docker pull "$NOTEBOOK_IMAGE"
docker run \
  -v /ssl/:/ssl/ \
  --net=host -d \
  -e CONFIGPROXY_AUTH_TOKEN=$TOKEN \
  --name=proxy \
  jupyter/configurable-http-proxy \
    --default-target 'http://127.0.0.1:9999' \
    --ssl-key /ssl/kimstebel.key \
    --ssl-cert /ssl/kimstebel.crt \
    --ssl-ca /ssl/kimstebel.ca
docker run \
  --net=host -d \
  -e CONFIGPROXY_AUTH_TOKEN=$TOKEN \
  --name=tmpnb \
  -v /var/run/docker.sock:/docker.sock \
  jupyter/tmpnb \
  python orchestrate.py \
    --image="$NOTEBOOK_IMAGE" \
    --command="ipython notebook --no-browser --NotebookApp.base_url={base_path} --ip=0.0.0.0 --port {port} --NotebookApp.allow_origin='*' " \
    --cull-timeout=300 \
    --cull_period=60 \
    --allow_origin="*" \
    --pool_size="$POOL_SIZE" \
    --pool_name=jupyter

